### ISSUE TITLE
Distribution request

### ISSUE THREAD

**Issue by archey** [d4rkcat/dnsbrute#1]
I am  a developer for the ArchAssault project, we would like distribute your tool but it does not have a license. Can you please add a license file to it and we will get it added?

Thanks

**Comment by d4rkcat** [comment]
Hi there,
  Got the License added for you. GPL v2.
stackflow.py is also pretty popular.
Thanks for your interest in my scripts. 
  d4rkcat

**Comment by archey** [comment]
I will add the stackflow script as well as long as it has a license.

**Comment by d4rkcat** [comment]
great, thanks dude!
Both scripts have Licenses added.
Let me know if you need anything else.
Nice looking distro might have to snag a copy to try it out.

**Comment by archey** [comment]
Sure no problem, feel free to check us out twitter@ArchAssault or come hang out in IRC #ArchAssault on freenode. I am following you on GH, but I wont add stars cause I read your commits about it LOL.

**Comment by d4rkcat** [comment]
Haha you can give me stars my man, just not on the g0tr00t script.
I will pop in the IRC some time. my twitter is @d4rkcat. 
Can wait to get a phantom2 to try this OS on, such a cool idea to support all those architectures.

**Comment by archey** [comment]
Sure no problem, I saw the follow on twitter. We support every architecture that is supported by ArchARM as they are one of our upstreams.
